name: Connect to GCP and List Instances

on:
  push:
    branches:
        - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider:  ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # List the instances in the project
    - name: List Instances
      run: |-
        gcloud compute instances list --project $PROJECT_ID
    - name: Verify Packer Installation
      run: packer --version 
    - name: Install Packer plugin googlecompute
      run: |
          packer plugin install googlecompute
    - name: Build GCP Windows Image
      run: |
          ls -all
          packer build packer/package.json